### ISSUE TITLE
Netbeans fails to load component JXMapkit3

### ISSUE THREAD

**Issue by krandalf75** [msteiger/jxmapviewer2#83]
Netbeans give an error when opening the design of a panel with a jxMapKit3 component.

![image](https://user-images.githubusercontent.com/1617097/73742266-548f8580-474c-11ea-8f65-628f60a29388.png)

With the release 2.1 it work well.

**Comment by msteiger** [comment]
Thanks, that is quite odd. I will have a look.

**Comment by msteiger** [comment]
Do you have more details on the error? The package declaration should be correct, so it's probably unrelated to JXMapViewer afaics.

**Comment by krandalf75** [comment]
If I press "Show Exceptions" I get this stack trace:

java.lang.NoClassDefFoundError: Could not initialize class org.jxmapviewer.viewer.DefaultTileFactory
	at org.jxmapviewer.JXMapKit.<init>(JXMapKit.java:109)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.netbeans.modules.form.CreationFactory.createDefaultInstance(CreationFactory.java:180)
	at org.netbeans.modules.form.RADComponent.createBeanInstance(RADComponent.java:252)
	at org.netbeans.modules.form.RADComponent.initInstance(RADComponent.java:191)
	at org.netbeans.modules.form.GandalfPersistenceManager.restoreComponent(GandalfPersistenceManager.java:780)
	at org.netbeans.modules.form.GandalfPersistenceManager.loadComponent(GandalfPersistenceManager.java:968)
	at org.netbeans.modules.form.GandalfPersistenceManager.loadForm(GandalfPersistenceManager.java:503)
	at org.netbeans.modules.form.GandalfPersistenceManager.loadForm(GandalfPersistenceManager.java:283)
	at org.netbeans.modules.form.FormEditor$2.run(FormEditor.java:352)
	at org.netbeans.modules.form.FormLAF$2.run(FormLAF.java:293)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:138)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:98)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:94)
	at org.openide.util.Mutex.readAccess(Mutex.java:250)
	at org.netbeans.modules.form.FormLAF.executeWithLookAndFeel(FormLAF.java:276)
	at org.netbeans.modules.form.FormEditor.loadFormData(FormEditor.java:349)
	at org.netbeans.modules.nbform.FormEditorSupport.loadOpeningForm(FormEditorSupport.java:461)
	at org.netbeans.modules.nbform.FormDesignerTC.loadForm(FormDesignerTC.java:279)
	at org.netbeans.modules.nbform.FormDesignerTC.access$300(FormDesignerTC.java:87)
	at org.netbeans.modules.nbform.FormDesignerTC$PreLoadTask$1.run(FormDesignerTC.java:268)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by krandalf75** [comment]
TileFactoryInfo info = new OSMTileFactoryInfo();
        TileFactory tileFactory = new DefaultTileFactory(info);
        setTileFactory(tileFactory);

There is no problem with constructor OSMTileFactoryInfo.  OSMTileFactoryInfo has the same package that jXMapkit3 but DefaultTileFactory has different package. Perhaps tNetbeans only load classes of the same package ?

**Comment by krandalf75** [comment]
If I move DefaultTileFactory to the same package as jXMapKit works: 

![image](https://user-images.githubusercontent.com/1617097/78472822-21617680-773c-11ea-8335-ccd1bad6c38a.png)

Perhaps is a Netbeans bug editor. I don't know.
