### ISSUE TITLE
zoomToBestFit ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dansch1** [msteiger/jxmapviewer2#90]
```java
while (bestZoom >= info.getMinimumZoomLevel() &&
               bounds.getWidth() < viewport.getWidth() * maxFraction &&
               bounds.getHeight() < viewport.getHeight() * maxFraction)
{
    bestZoom--;
    bounds = generateBoundingRect(positions, bestZoom);
}
```
'zoomToBestFit' (line 718-724 in JXMapViewer) can cause ArrayIndexOutOfBoundsException if positions are really close together (using OSMTileFactoryInfo).

**Comment by msteiger** [comment]
Sorry for the delay? When exactly do you get the exception? And where? Is it due to "bestZoom" being negative?

**Comment by dansch1** [comment]
Exactly. OSMTileFactoryInfo has a minimumZoomLevel of 0, so if i call "zoomToBestFit" with positions that are close together "bestZoom" is -1 and causes an ArrayIndexOutOfBoundsException.

```java
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at org.jxmapviewer.viewer.TileFactoryInfo.getMapCenterInPixelsAtZoom(TileFactoryInfo.java:195)
	at org.jxmapviewer.viewer.util.GeoUtil.getBitmapCoordinate(GeoUtil.java:100)
	at org.jxmapviewer.viewer.util.GeoUtil.getBitmapCoordinate(GeoUtil.java:86)
	at org.jxmapviewer.viewer.TileFactory.geoToPixel(TileFactory.java:92)
	at org.jxmapviewer.JXMapViewer.generateBoundingRect(JXMapViewer.java:731)
	at org.jxmapviewer.JXMapViewer.zoomToBestFit(JXMapViewer.java:723)
```

**Comment by msteiger** [comment]
Do you find the time to create PR for it? I am currently swamped with other topics, sorry.

**Comment by dansch1** [comment]
Sure, but I can't create a branch.

**Comment by msteiger** [comment]
You can fork this repository (top right corner) and create a branch in your own workspace. When the changes are done, you can create a Pull Request to this repository.

**Comment by msteiger** [comment]
Fixed!
